##-- DDL语句
##
##-- V1.0
##
##-- 机构列表角色控制支持 提交日期2017/3/25
CREATE TABLE IF NOT EXISTS `t_custinfo_role` (
	`L_REG_OPERID` BIGINT(18) NULL DEFAULT '0' COMMENT '创建人(操作员)ID号',
	`C_REG_OPERNAME` VARCHAR(40) NULL DEFAULT NULL COMMENT '创建人(操作员)姓名',
	`D_REG_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '创建日期',
	`T_REG_TIME` VARCHAR(8) NULL DEFAULT NULL COMMENT '创建时间',
	`L_MODI_OPERID` BIGINT(18) NULL DEFAULT NULL COMMENT '修改人(操作员)ID号',
	`C_MODI_OPERNAME` VARCHAR(40) NULL DEFAULT NULL COMMENT '修改人(操作员)姓名',
	`D_MODI_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '修改日期',
	`T_MODI_TIME` VARCHAR(8) NULL DEFAULT NULL COMMENT '修改时间',
	`L_CUSTNO` BIGINT(18) NOT NULL COMMENT '用户编号',
	`C_OPERROLE` VARCHAR(40) NOT NULL COMMENT '用户角色',
	`C_OPERORG` VARCHAR(40) NOT NULL,
	PRIMARY KEY (`L_CUSTNO`, `C_OPERROLE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB$$

