##-- DDL语句
##
##-- V1.0
##
##-- 表结构非空修改 提交日期2016/11/18


##-- task 202

##-- 创建日对账单表	提交日期2017/05/12
drop PROCEDURE if EXISTS create_table_cpsStatement$$
	create procedure create_table_cpsStatement() 
	BEGIN
		IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_cps_daily_statement')
		THEN
		CREATE TABLE `t_cps_daily_statement` (
			`ID` BIGINT(18) NOT NULL COMMENT '编号',
			`C_REFNO` VARCHAR(18) NULL DEFAULT NULL COMMENT '凭证编号',
			`C_UNIT` VARCHAR(10) NULL DEFAULT '' COMMENT '金额单位（默认元）',
			`C_CURRENY` VARCHAR(10) NULL DEFAULT 'RMB' COMMENT '币种',
			`D_PAY_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '支付日期',
			`T_PAY_TIME` VARCHAR(8) NULL DEFAULT NULL COMMENT '支付时间',
			`F_TOTAL_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '总金额',
			`N_TOTAL_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '总笔数',
			`F_PAY_TOTAL_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付总金额',
			`N_PAY_TOTAL_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付总笔数',
			`F_PAY_SUCCESS_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付成功金额',
			`N_PAY_SUCCESS_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付成功笔数',
			`F_PAY_FAILURE_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付失败金额',
			`N_PAY_FAILURE_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付失败笔数',
			`L_OWN_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '企业客户号',
			`C_OWN_CUSTNAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '企业名称',
			`C_OWN_OPERORG` VARCHAR(100) NULL DEFAULT NULL COMMENT '机构',
			`C_MAKE_CUSTNAME` VARCHAR(20) NULL DEFAULT NULL COMMENT '制表公司名称',
			`C_MAKE_OPERNAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '制表人',
			`D_MAKE_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '制表日期',
			`T_MAKE_TIME` VARCHAR(8) NULL DEFAULT NULL COMMENT '制表时间',
			`C_BUSIN_STATUS` VARCHAR(2) NULL DEFAULT NULL COMMENT '业务状态，0未处理，1已确认，2已审核，3已生成过月账单,9已作废',
			`C_LAST_STATUS` VARCHAR(2) NULL DEFAULT NULL,
			`N_BATCHNO` BIGINT(20) NULL DEFAULT NULL,
			`C_OPERORG` VARCHAR(200) NULL DEFAULT ' ',
			`L_REG_OPERID` BIGINT(18) NULL DEFAULT '0',
			`C_REG_OPERNAME` VARCHAR(40) NULL DEFAULT ' ',
			`D_REG_DATE` VARCHAR(8) NULL DEFAULT ' ',
			`T_REG_TIME` VARCHAR(8) NULL DEFAULT ' ',
			`L_MODI_OPERID` BIGINT(18) NULL DEFAULT '0',
			`C_MODI_OPERNAME` VARCHAR(40) NULL DEFAULT ' ',
			`D_MODI_DATE` VARCHAR(8) NULL DEFAULT ' ',
			`T_MODI_TIME` VARCHAR(8) NULL DEFAULT ' ',
			`N_VERSION` BIGINT(20) NULL DEFAULT '0',
			`D_END_INTEREST_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '结息日期',
			`F_INTEREST` DECIMAL(16,2) NULL DEFAULT '0.00' COMMENT '利息',
			`F_INTEREST_RATE` DECIMAL(16,2) NULL DEFAULT '0.00' COMMENT '利率',
			`L_FILE_ID` BIGINT(20) NULL DEFAULT '0' COMMENT '文件ID',
			PRIMARY KEY (`ID`),
			UNIQUE INDEX `IDXT_CPS_DAILY_STATEMENT_REFNO` (`C_REFNO`),
			INDEX `IDXT_CPS_D_PAY_DATE_L_OWN_CUSTNO` (`D_PAY_DATE`, `L_OWN_CUSTNO`)
		);
		END IF;
	END$$
call create_table_cpsStatement()$$
drop PROCEDURE if EXISTS create_table_cpsStatement$$


##-- 创建日对账单记录表	提交日期2017/05/12
drop PROCEDURE if EXISTS create_table_cpsStatement$$
	create procedure create_table_cpsStatement() 
	BEGIN
		IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_cps_daily_statement_record')
		THEN
		CREATE TABLE `t_cps_daily_statement_record` (
			`ID` BIGINT(18) NOT NULL COMMENT '编号',
			`L_DAILY_STATEMENT_ID` BIGINT(18) NOT NULL COMMENT '日报表编号',
			`C_DAILY_STATEMENT_REFNO` VARCHAR(18) NOT NULL COMMENT '日报表凭证编号',
			`L_PAY_RECORD_ID` BIGINT(18) NULL DEFAULT NULL COMMENT '佣金支付对账记录编号',
			`C_PAY_RECORD_REFNO` VARCHAR(18) NULL DEFAULT NULL COMMENT '佣金支付对账记录凭证号',
			`L_RECORD_ID` BIGINT(18) NULL DEFAULT NULL COMMENT '佣金记录编号',
			`C_RECORD_REFNO` VARCHAR(18) NULL DEFAULT NULL COMMENT '佣金记录凭证号',
			`D_IMPORT_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '导入日期',
			`T_IMPORT_TIME` VARCHAR(8) NULL DEFAULT NULL COMMENT '导入时间',
			`C_PAYNO` VARCHAR(18) NULL DEFAULT NULL COMMENT '支付流水号',
			`D_PAY_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '支付日期',
			`T_PAY_TIME` VARCHAR(8) NULL DEFAULT NULL COMMENT '支付时间',
			`F_PAY_BALANCE` DECIMAL(16,2) NULL DEFAULT '0.00' COMMENT '支付金额',
			`C_PAY_TARGET_BANK` VARCHAR(50) NULL DEFAULT NULL COMMENT '收款银行',
			`C_PAY_TARGET_BANKNAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '收款银行名称',
			`C_PAY_TARGET_BANK_FULLNAME` VARCHAR(200) NULL DEFAULT NULL COMMENT '收款银行全称',
			`C_PAY_TARGET_BANK_ACCO` VARCHAR(50) NULL DEFAULT NULL COMMENT '收款银行账户',
			`C_PAY_TARGET_BANK_ACCO_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '收款银行帐户名',
			`C_PAY_TARGET_MOBILENO` VARCHAR(20) NULL DEFAULT NULL COMMENT '手机号码',
			`C_PAY_BANK` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付银行',
			`C_PAY_BANKNAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '支付银行名称',
			`C_PAY_BANK_FULLNAME` VARCHAR(200) NULL DEFAULT NULL COMMENT '支付银行全称',
			`C_PAY_BANK_ACCO` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付银行帐户',
			`C_PAY_BANK_ACCO_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '支付银行账户名',
			`C_PAY_RESULT` VARCHAR(2) NULL DEFAULT NULL COMMENT '支付结果：0未处理，1支付成功，2支付失败',
			`C_PAY_COMMENT` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
			`C_BUSIN_STATUS` VARCHAR(2) NULL DEFAULT NULL COMMENT '业务状态：0未处理，1已确认，2已复核',
			`C_LAST_STATUS` VARCHAR(2) NULL DEFAULT NULL,
			`L_CUSTNO` BIGINT(20) NULL DEFAULT NULL COMMENT '客户ID',
			`C_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '客户名称',
			`C_OPERORG` VARCHAR(200) NULL DEFAULT ' ',
			`L_REG_OPERID` BIGINT(18) NULL DEFAULT '0',
			`C_REG_OPERNAME` VARCHAR(40) NULL DEFAULT ' ',
			`D_REG_DATE` VARCHAR(8) NULL DEFAULT ' ',
			`T_REG_TIME` VARCHAR(8) NULL DEFAULT ' ',
			`N_VERSION` BIGINT(20) NULL DEFAULT '0',
			INDEX `IDX_T_CPS_DAILY_STATEMENT_ID_REFNO` (`L_DAILY_STATEMENT_ID`, `C_DAILY_STATEMENT_REFNO`)
		);
		END IF;
	END$$
call create_table_cpsStatement()$$
drop PROCEDURE if EXISTS create_table_cpsStatement$$




##-- 创建月对账单表	提交日期2017/05/12
drop PROCEDURE if EXISTS create_table_cpsStatement$$
	create procedure create_table_cpsStatement() 
	BEGIN
		IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_cps_monthly_statement')
		THEN
		CREATE TABLE `t_cps_monthly_statement` (
			`ID` BIGINT(18) NOT NULL COMMENT '编号',
			`C_REFNO` VARCHAR(18) NOT NULL COMMENT '凭证号',
			`C_UNIT` VARCHAR(10) NULL DEFAULT '' COMMENT '金额单位（默认元）',
			`C_CURRENY` VARCHAR(10) NULL DEFAULT 'RMB' COMMENT '币种',
			`D_PAY_BEGIN_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '开始时间',
			`D_PAY_END_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '结束时间',
			`F_TOTAL_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '总金额',
			`N_TOTAL_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '总笔数',
			`F_PAY_TOTAL_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付总金额',
			`N_PAY_TOTAL_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付总笔数',
			`F_PAY_SUCCESS_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付成功金额',
			`N_PAY_SUCCESS_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付成功笔数',
			`F_PAY_FAILURE_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付失败金额',
			`N_PAY_FAILURE_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付失败笔数',
			`L_OWN_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '企业客户号',
			`C_OWN_CUSTNAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '企业名称',
			`C_OWN_OPERORG` VARCHAR(100) NULL DEFAULT NULL COMMENT '机构',
			`C_MAKE_CUSTNAME` VARCHAR(20) NULL DEFAULT NULL COMMENT '制表公司名称',
			`C_MAKE_OPERNAME` VARCHAR(100) NULL DEFAULT NULL COMMENT '操作员名称',
			`D_MAKE_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '制表日期',
			`T_MAKE_TIME` VARCHAR(8) NULL DEFAULT NULL COMMENT '制表时间',
			`C_BUSIN_STATUS` VARCHAR(2) NULL DEFAULT NULL COMMENT '业务状态，0未处理，1已确认，2已审核，3账单建立投递  4账单已投递',
			`C_LAST_STATUS` VARCHAR(2) NULL DEFAULT NULL,
			`D_END_INTEREST_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '结息日期',
			`F_INTEREST` DECIMAL(16,2) NULL DEFAULT NULL COMMENT '利息',
			`F_INTEREST_RATE` DECIMAL(16,2) NULL DEFAULT NULL COMMENT '利率',
			`F_TAX_BALANCE` DECIMAL(16,2) NULL DEFAULT NULL COMMENT '税额',
			`F_TAX_RATE` DECIMAL(16,2) NULL DEFAULT NULL COMMENT '税利率',
			`N_BATCHNO` BIGINT(20) NULL DEFAULT NULL COMMENT '月报表文件',
			`C_OPERORG` VARCHAR(200) NULL DEFAULT ' ',
			`L_REG_OPERID` BIGINT(18) NULL DEFAULT '0',
			`C_REG_OPERNAME` VARCHAR(40) NULL DEFAULT ' ',
			`D_REG_DATE` VARCHAR(8) NULL DEFAULT ' ',
			`T_REG_TIME` VARCHAR(8) NULL DEFAULT ' ',
			`L_MODI_OPERID` BIGINT(18) NULL DEFAULT '0',
			`C_MODI_OPERNAME` VARCHAR(40) NULL DEFAULT ' ',
			`D_MODI_DATE` VARCHAR(8) NULL DEFAULT ' ',
			`T_MODI_TIME` VARCHAR(8) NULL DEFAULT ' ',
			`N_VERSION` BIGINT(20) NULL DEFAULT '0',
			`D_BILL_MONTH` VARCHAR(6) NULL DEFAULT '0' COMMENT '对账月份',
			`L_FILE_ID` BIGINT(20) NULL DEFAULT NULL,
			PRIMARY KEY (`ID`),
			UNIQUE INDEX `IDXT_CPS_MONTHLY_STATEMENT_C_REFNO` (`C_REFNO`)
		);
		END IF;
	END$$
call create_table_cpsStatement()$$
drop PROCEDURE if EXISTS create_table_cpsStatement$$




##-- 创建月对账单记录表	提交日期2017/05/12
drop PROCEDURE if EXISTS create_table_cpsStatement$$
	create procedure create_table_cpsStatement() 
	BEGIN
		IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_cps_monthly_statement_record')
		THEN
		CREATE TABLE `t_cps_monthly_statement_record` (
			`ID` BIGINT(18) NOT NULL COMMENT '编号',
			`L_MONTHLY_STATEMENT_ID` BIGINT(18) NOT NULL COMMENT '月报表ID',
			`C_MONTHLY_STATEMENT_REFNO` VARCHAR(18) NOT NULL COMMENT '月报表凭证编号',
			`L_DAILY_STATEMENT_ID` BIGINT(18) NOT NULL COMMENT '日报表ID',
			`C_DAILY_STATEMENT_REFNO` VARCHAR(18) NOT NULL COMMENT '日报表凭证编号',
			`D_PAY_DATE` VARCHAR(8) NOT NULL COMMENT '支付日期',
			`F_PAY_TOTAL_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付总金额',
			`N_PAY_TOTAL_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付总笔数',
			`F_PAY_SUCCESS_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付成功金额',
			`N_PAY_SUCCESS_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付成功笔数',
			`F_PAY_FAILURE_BALANCE` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付失败金额',
			`N_PAY_FAILURE_AMOUNT` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '支付失败笔数',
			`F_INTEREST` DECIMAL(16,2) NULL DEFAULT NULL COMMENT '利息',
			`F_INTEREST_RATE` DECIMAL(16,2) NULL DEFAULT NULL COMMENT '佣金年利率',
			`L_CUSTNO` BIGINT(20) NULL DEFAULT NULL COMMENT '客户ID',
			`C_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '客户名称',
			`C_OPERORG` VARCHAR(200) NULL DEFAULT ' ',
			`L_REG_OPERID` BIGINT(18) NULL DEFAULT '0',
			`C_REG_OPERNAME` VARCHAR(40) NULL DEFAULT ' ',
			`D_REG_DATE` VARCHAR(8) NULL DEFAULT ' ',
			`T_REG_TIME` VARCHAR(8) NULL DEFAULT ' ',
			`N_VERSION` BIGINT(20) NULL DEFAULT '0',
			PRIMARY KEY (`ID`),
			INDEX `IDXT_CPS_MONTHLY_STATEMENT_RECORD_ID_REFNO` (`L_MONTHLY_STATEMENT_ID`, `C_MONTHLY_STATEMENT_REFNO`)
		);
		END IF;
	END$$
call create_table_cpsStatement()$$
drop PROCEDURE if EXISTS create_table_cpsStatement$$


##--新增结束金额字段 2017/05/16
drop PROCEDURE if EXISTS change_table_col$$
create procedure change_table_col() BEGIN   
IF NOT EXISTS (SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA in (select database()) AND table_name='t_cps_monthly_statement' AND COLUMN_NAME='F_INTEREST_BALANCE')
THEN   
   ALTER TABLE `t_cps_monthly_statement` ADD COLUMN `F_INTEREST_BALANCE` DECIMAL(16,2) default 0.00 COMMENT '结算金额';
END IF;
END$$
call change_table_col()$$
drop PROCEDURE if EXISTS change_table_col$$

##--变更索引
drop PROCEDURE if EXISTS change_table_pri_index$$
create procedure change_table_pri_index() BEGIN   
IF EXISTS (SELECT * FROM information_schema.STATISTICS WHERE TABLE_SCHEMA in (select database()) AND table_name='t_cps_daily_statement_record' and index_name='PRIMARY')
THEN   
   alter table t_cps_daily_statement_record drop primary key;
END IF;
END$$
call change_table_pri_index()$$
drop PROCEDURE if EXISTS change_table_pri_index$$


drop PROCEDURE if EXISTS change_table_index$$
create procedure change_table_index() BEGIN   
IF NOT EXISTS (SELECT * FROM information_schema.STATISTICS WHERE TABLE_SCHEMA in (select database()) AND table_name='t_cps_daily_statement_record' and index_name='IDX_ID')
THEN   
   alter table t_cps_daily_statement_record add index IDX_ID(ID);
END IF;
END$$
call change_table_index()$$
drop PROCEDURE if EXISTS change_table_index$$



