##-- DDL语句
##
##-- V1.0
##
##-- 产品配置相关表 提交日期2017/4/28

DROP TABLE IF EXISTS t_scf_asset_dict$$
CREATE TABLE `t_scf_asset_dict` (
	`ID` BIGINT(18) NOT NULL COMMENT 'ID',
	`C_DICT_TYPE` VARCHAR(2) NULL DEFAULT NULL COMMENT '资产类型,商业承兑汇票:1,应付账款:2,贸易合同:3,商业发票:4,采购订单或订货单:5,对账单:6,出货单或出库单:7',
	`C_DATA_SOURCE` VARCHAR(2) NULL DEFAULT NULL COMMENT '数据来源，1：核心企业资金系统，2：供应商录入',
	`C_FORM_DATA` VARCHAR(2) NULL DEFAULT NULL COMMENT '表单数据要求，0：无要求，1：有要求',
	`C_ATTACH` VARCHAR(2) NULL DEFAULT NULL COMMENT '附件要求，0：无要求，1：有要求',
	`C_BUSIN_STATUS` VARCHAR(2) NULL DEFAULT NULL COMMENT '状态，0：不可用，1：可用',
	`C_DESCRIPTION` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COMMENT='资产类型表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB$$

DROP TABLE IF EXISTS t_scf_product_asset_dict_relation$$
CREATE TABLE `t_scf_product_asset_dict_relation` (
	`L_ASSEST_ID` BIGINT(18) NOT NULL COMMENT '资产类型ID',
	`C_PRODUCT_CODE` VARCHAR(50) NULL DEFAULT NULL COMMENT '产品编号',
	`ID` BIGINT(18) NULL DEFAULT NULL,
	`C_ASSEST_TYPE` VARCHAR(2) NULL DEFAULT NULL COMMENT '资产类型(1主体资产/2辅助材料)'
)
COMMENT='产品与资产类型关系表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB$$

DROP TABLE IF EXISTS t_scf_asset_dict_attach_relation$$
CREATE TABLE `t_scf_asset_dict_attach_relation` (
	`ID` BIGINT(18) NOT NULL COMMENT '附件类型ID',
	`L_ASSESTID` BIGINT(18) NOT NULL COMMENT '资产类型ID',
	`C_ATTCH_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '附件类型名',
	PRIMARY KEY (`ID`, `L_ASSESTID`)
)
COMMENT='资产类型关联附件类型表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB$$


DROP TABLE IF EXISTS t_scf_product_config$$
CREATE TABLE `t_scf_product_config` (
	`ID` BIGINT(18) NOT NULL,
	`C_PRODUCT_CODE` VARCHAR(50) NULL DEFAULT NULL COMMENT '产品编号',
	`C_PRODUCT_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '产品名称',
	`C_FACTOR_TYPE` VARCHAR(2) NULL DEFAULT NULL COMMENT '保理类型，1：国内有追索权保理，2：国内无追索权保理',
	`C_ACTION_MODEL` VARCHAR(2) NULL DEFAULT NULL COMMENT '操作方式，1：正向保理 ，2： 反向保理',
	`C_FINANCE_TYPE` VARCHAR(2) NULL DEFAULT NULL COMMENT '融资类型：1应收账款保理融资,2商票保理',
	`C_FINANCE_MODEL` VARCHAR(2) NULL DEFAULT NULL COMMENT '融资方式: 1:折扣方式;2:比例方式',
	`F_FINANCE_PROPORTION` BIGINT(18) NULL DEFAULT NULL COMMENT '比例',
	`F_RATIO` BIGINT(18) NULL DEFAULT NULL COMMENT '通用利率',
	`F_MIN_FACTOR_AMMOUNT` BIGINT(18) NULL DEFAULT NULL COMMENT '最小融资额',
	`F_MAX_FACTOR_AMMOUNT` BIGINT(18) NULL DEFAULT NULL COMMENT '最大融资额',
	`C_FEATURE` VARCHAR(500) NULL DEFAULT NULL COMMENT '产品特征',
	`C_FIT_CROWD` VARCHAR(500) NULL DEFAULT NULL COMMENT '适用范围',
	`C_CORE_CREDICT` VARCHAR(2) NULL DEFAULT NULL COMMENT '核心企业授信占用；0不占用， 1:占用，',
	`L_FACTORNO` BIGINT(18) NULL DEFAULT NULL COMMENT '保理公司',
	`L_BUSIN_ID` BIGINT(18) NULL DEFAULT NULL COMMENT '业务类型id',
	`N_MINDAYS` INT(11) NULL DEFAULT NULL COMMENT '最短放款天数',
	`N_MAXDAYS` INT(11) NULL DEFAULT NULL COMMENT '最长放款天数',
	`C_FACTORNAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '保理公司名称',
	`C_BUSIN_STATUS` VARCHAR(2) NULL DEFAULT NULL COMMENT '0:登记;1:上架;2:下架,3:草稿',
	`C_OPERORG` VARCHAR(200) NULL DEFAULT ' ' COMMENT '操作机构',
	`L_REG_OPERID` BIGINT(18) NULL DEFAULT '0',
	`C_REG_OPERNAME` VARCHAR(40) NULL DEFAULT ' ',
	`D_REG_DATE` VARCHAR(8) NULL DEFAULT ' ',
	`T_REG_TIME` VARCHAR(8) NULL DEFAULT ' ',
	`L_MODI_OPERID` BIGINT(18) NULL DEFAULT '0',
	`C_MODI_OPERNAME` VARCHAR(40) NULL DEFAULT ' ',
	`D_MODI_DATE` VARCHAR(8) NULL DEFAULT ' ',
	`T_MODI_TIME` VARCHAR(8) NULL DEFAULT ' ',
	`N_VERSION` BIGINT(30) NULL DEFAULT '0',
	`L_SHELVES_OPERID` BIGINT(18) NULL DEFAULT '0' COMMENT '产品上架操作员ID号',
	`C_SHELVES_OPERNAME` VARCHAR(40) NULL DEFAULT ' ' COMMENT '产品上架操作员姓名',
	`C_SHELVES_DATE` VARCHAR(8) NULL DEFAULT ' ' COMMENT '产品上架日期',
	`T_SHELVES_TIME` VARCHAR(8) NULL DEFAULT ' ' COMMENT '产品上架时间',
	`L_OFFLINE_OPERID` BIGINT(18) NULL DEFAULT '0' COMMENT '产品下架操作员ID号',
	`C_OFFLINE_OPERNAME` VARCHAR(40) NULL DEFAULT ' ' COMMENT '产品下架操作员姓名',
	`D_OFFLINE_DATE` VARCHAR(8) NULL DEFAULT ' ' COMMENT '产品下架日期',
	`T_OFFLINE_TIME` VARCHAR(8) NULL DEFAULT ' ' COMMENT '产品下架时间',
	PRIMARY KEY (`ID`)
)
COMMENT='产品配置表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB$$


DROP TABLE IF EXISTS t_scf_product_core_relation$$
CREATE TABLE `t_scf_product_core_relation` (
	`ID` BIGINT(18) NOT NULL,
	`C_PRODUCT_CODE` VARCHAR(50) NULL DEFAULT NULL COMMENT '产品编号',
	`L_CORE_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '核心企业编号',
	`C_CORE_CUSTNAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '核心企业',
	PRIMARY KEY (`ID`)
)
COMMENT='产品与核心企业关系表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB$$




