##-- DDL���
##
##-- V1.0
##
##-- ��ṹ�ǿ��޸�		�ύ����2016/11/18
ALTER TABLE `t_scf_receivable`
	CHANGE COLUMN `C_GOODSNAME` `C_GOODSNAME` VARCHAR(40) NULL COMMENT '��Ʒ���' AFTER `C_DEBTOR`;
	
##�����Ż���Ӧ�������ֶ�   �ύ����2016/11/25
ALTER TABLE `t_cust_open_account_tmp`
	ADD COLUMN `C_TAX_NO` VARCHAR(120) NULL DEFAULT NULL COMMENT '˰��Ǽ�֤��' AFTER `C_CORELIST`,
	ADD COLUMN `C_OPEN_LICENSE` VARCHAR(120) NULL DEFAULT NULL COMMENT '�������֤��׼��' AFTER `C_TAX_NO`;
ALTER TABLE `t_cust_mech_bankacco_tmp`
	ADD COLUMN `C_OPEN_LICENSE` VARCHAR(120) NULL DEFAULT NULL COMMENT '�������֤��׼��' AFTER `N_BATCHNO`;
	ALTER TABLE `t_cust_mech_bankacco`
	ADD COLUMN `C_OPEN_LICENSE` VARCHAR(120) NULL DEFAULT NULL COMMENT '�������֤��׼��' AFTER `N_BATCHNO`;
	
ALTER TABLE `t_cust_open_account_tmp`
	ADD COLUMN `C_WECHAT_OPENID` VARCHAR(120) NULL DEFAULT NULL COMMENT '΢���û���ʶ' AFTER `C_OPEN_LICENSE`,
	ADD COLUMN `C_DEAL_PASSWORD` VARCHAR(120) NULL DEFAULT NULL COMMENT '��������(��΢����)' AFTER `C_WECHAT_OPENID`,
	ADD COLUMN `C_ROLE` VARCHAR(18) NULL DEFAULT NULL COMMENT '��ɫ����Ӧ�̡�������' AFTER `C_DEAL_PASSWORD`;
##�ļ������ֶγ���   �ύ����2016/11/29
ALTER TABLE `t_cust_fileaduit`
	CHANGE COLUMN `C_TYPE` `C_TYPE` VARCHAR(60) NULL DEFAULT NULL AFTER `C_STATUS`;

##����������������״̬   	�ύ����2016/12/2
ALTER TABLE `t_cust_open_account_tmp`
	CHANGE COLUMN `C_BUSIN_STATUS` `C_BUSIN_STATUS` CHAR(1) NULL DEFAULT NULL COMMENT '0δʹ��  1ʹ����  2��ʹ�� 3����4��������' AFTER `T_MODI_TIME`;
##�����Ż��������ֶ�			�ύ����2016/12/6
ALTER TABLE `t_cust_open_account_tmp`
	ADD COLUMN `C_OPER_OTHER_IDENTTYPE` VARCHAR(20) NULL DEFAULT NULL COMMENT '����������֤������' AFTER `C_OPER_IDENTTYPE`,
	ADD COLUMN `C_LAW_OTHER_IDENTTYPE` VARCHAR(20) NULL DEFAULT NULL COMMENT '��������֤������' AFTER `C_LAW_IDENTTYPE`,
	ADD COLUMN `C_DATA_SOURCE` CHAR(1) NOT NULL DEFAULT NULL COMMENT '�����Դ:0:PC��������,1:PCƽ̨��¼,2:΢��ƽ̨��¼' AFTER `C_ROLE`;
ALTER TABLE `t_cust_open_account_tmp`
	ADD COLUMN `D_ACTIVE_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '��������' AFTER `C_DATA_SOURCE`,
	ADD COLUMN `T_ACTIVE_TIME` VARCHAR(8) NULL DEFAULT NULL COMMENT '����ʱ��' AFTER `D_ACTIVE_DATE`;
	
	
##����������ϵ�����ʱ�� �ύ����2016/12/08
CREATE TABLE `t_cust_fileaduit_temp` (
	`ID` DECIMAL(18,0) NULL DEFAULT NULL,
	`L_CUSTNO` DECIMAL(18,0) NULL DEFAULT NULL,
	`N_COUNT` DECIMAL(5,0) NULL DEFAULT NULL,
	`C_STATUS` VARCHAR(1) NULL DEFAULT NULL,
	`C_TYPE` VARCHAR(60) NULL DEFAULT NULL,
	`C_DESCRIPTION` VARCHAR(200) NULL DEFAULT NULL,
	`D_REGDATE` VARCHAR(8) NULL DEFAULT NULL,
	`D_REGTIME` VARCHAR(8) NULL DEFAULT NULL,
	`D_MODIDATE` VARCHAR(15) NULL DEFAULT NULL,
	`C_OPERNO` VARCHAR(8) NULL DEFAULT NULL,
	`L_ADUIT_CUSTNO` DECIMAL(18,0) NULL DEFAULT NULL,
	`C_ADUITORNO` VARCHAR(8) NULL DEFAULT NULL,
	`D_ADUIT_DATE` VARCHAR(15) NULL DEFAULT NULL,
	UNIQUE INDEX `PK_CUST_FILEADUIT` (`ID`, `L_CUSTNO`, `C_TYPE`)
);

