##-- DDL语句
##
##-- V1.0
##
##-- 表结构非空修改		提交日期2016/11/18
ALTER TABLE `t_scf_receivable`
	CHANGE COLUMN `C_GOODSNAME` `C_GOODSNAME` VARCHAR(40) NULL COMMENT '商品名称' AFTER `C_DEBTOR`;
	
##开户优化相应表增加字段   提交日期2016/11/25
ALTER TABLE `t_cust_open_account_tmp`
	ADD COLUMN `C_TAX_NO` VARCHAR(120) NULL DEFAULT NULL COMMENT '税务登记证号' AFTER `C_CORELIST`,
	ADD COLUMN `C_OPEN_LICENSE` VARCHAR(120) NULL DEFAULT NULL COMMENT '开户许可证核准号' AFTER `C_TAX_NO`;
ALTER TABLE `t_cust_mech_bankacco_tmp`
	ADD COLUMN `C_OPEN_LICENSE` VARCHAR(120) NULL DEFAULT NULL COMMENT '开户许可证核准号' AFTER `N_BATCHNO`;
	ALTER TABLE `t_cust_mech_bankacco`
	ADD COLUMN `C_OPEN_LICENSE` VARCHAR(120) NULL DEFAULT NULL COMMENT '开户许可证核准号' AFTER `N_BATCHNO`;
	
ALTER TABLE `t_cust_open_account_tmp`
	ADD COLUMN `C_WECHAT_OPENID` VARCHAR(120) NULL DEFAULT NULL COMMENT '微信用户标识' AFTER `C_OPEN_LICENSE`,
	ADD COLUMN `C_DEAL_PASSWORD` VARCHAR(120) NULL DEFAULT NULL COMMENT '交易密码(仅微信有)' AFTER `C_WECHAT_OPENID`,
	ADD COLUMN `C_ROLE` VARCHAR(18) NULL DEFAULT NULL COMMENT '角色：供应商、经销商' AFTER `C_DEAL_PASSWORD`;
##文件类型字段长度   提交日期2016/11/29
ALTER TABLE `t_cust_fileaduit`
	CHANGE COLUMN `C_TYPE` `C_TYPE` VARCHAR(60) NULL DEFAULT NULL AFTER `C_STATUS`;