##--合同编号生成 提交日期2017/01/06
delete from t_cfg_snogeneral where C_OPERTYPE in ('LIMIT_102202019_QEQHTZQR','LIMIT_102202019_QEQHTZTZ')$$
INSERT INTO `t_cfg_snogeneral` (`C_OPERTYPE`, `L_LASTNO`, `D_LASTDATE`, `C_SYSNO`, `C_TYPE`, `C_MSG`, `L_DATA_LEN`, `ID`) VALUES ('LIMIT_102202019_QEQHTZQR', 0, NULL, 'SCF', '3', NULL, 5, 50010)$$
INSERT INTO `t_cfg_snogeneral` (`C_OPERTYPE`, `L_LASTNO`, `D_LASTDATE`, `C_SYSNO`, `C_TYPE`, `C_MSG`, `L_DATA_LEN`, `ID`) VALUES ('LIMIT_102202019_QEQHTZTZ', 0, NULL, 'SCF', '3', NULL, 5, 50011)$$


##--添加帮助菜单  提交日期2017/01/12
delete from t_cfg_menu where id in (5,314,315,316)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (5, NULL, '帮助中心', '帮助中心', NULL, NULL, 0, 5, '帮助中心', '1', '20170112', '20170112', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (314, NULL, '帮助中心', '帮助中心', '', NULL, 5, 1, '', '1', '20170112', '20170112', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (315, NULL, '帮助中心', '帮助中心', '../../scf2/home.html#/help/helpCenter', NULL, 314, 1, '', '1', '20170112', '20170112', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (316, NULL, '帮助', '帮助', '../../scf2/home.html#/help/help', NULL, 314, 2, '', '0', '20170112', '20170112', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$


##--添加贸易台账菜单  提交日期2017/02/09
delete from t_cfg_menu where id in (330,331,332,333,334,335,336)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (330, NULL, '合同台账管理', '合同台账管理', NULL, NULL, 4, 10, '合同台账管理', '1', '20170123', '20170123', NULL, '0', 'SUPPLIER_USER,SELLER_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (331, NULL, '贸易合同台账登记', '贸易合同台账登记', '../../scf2/home.html#/sellerContract/list', NULL, 330, 1, '贸易合同台账登记', '1', '20170123', '20170123', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (332, NULL, '贸易合同台账审核', '贸易合同台账审核', '../../scf2/home.html#/sellerContract/aduit', NULL, 330, 2, '贸易合同台账审核', '1', '20170123', '20170123', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (333, NULL, '贸易合同台账查询', '贸易合同台账查询', '../../scf2/home.html#/sellerContract/query', NULL, 330, 3, '贸易合同台账查询', '1', '20170123', '20170123', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (334, NULL, '贸易合同台账登记', '贸易合同台账登记', '../../scf2/home.html#/supplierContract/list', NULL, 330, 1, '贸易合同台账登记', '1', '20170123', '20170123', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (335, NULL, '贸易合同台账审核', '贸易合同台账审核', '../../scf2/home.html#/supplierContract/aduit', NULL, 330, 1, '贸易合同台账审核', '1', '20170123', '20170123', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (336, NULL, '贸易合同台账查询', '贸易合同台账查询', '../../scf2/home.html#/supplierContract/query', NULL, 330, 1, '贸易合同台账查询', '1', '20170123', '20170123', NULL, '1', 'SUPPLIER_USER')$$


##--添加贸易台账配置  提交日期2017/02/09
delete from t_rule_busin where id in (50009,50010)$$
INSERT INTO `t_rule_busin` (`C_NAME`, `C_TYPE`, `C_EXECUTE_CONTENT`, `C_DESCRIPTION`, `C_GROUP`, `C_ERRORINFO`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `ID`, `C_VERSION`, `C_FUNC`, `C_ENTITY`) VALUES ('webAddContractLedger', NULL, NULL, '添加合同台账', NULL, NULL, '1', '20170119', '20170119', 50009, NULL, 'IContractLedgerService.webAddContractLedger', 'com.betterjr.modules.ledger.entity.ContractLedger')$$
INSERT INTO `t_rule_busin` (`C_NAME`, `C_TYPE`, `C_EXECUTE_CONTENT`, `C_DESCRIPTION`, `C_GROUP`, `C_ERRORINFO`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `ID`, `C_VERSION`, `C_FUNC`, `C_ENTITY`) VALUES ('webSaveContractLedger', NULL, NULL, '修改合同台账', NULL, NULL, '1', '20170119', '20170119', 50010, NULL, 'IContractLedgerService.webSaveContractLedger', 'com.betterjr.modules.ledger.entity.ContractLedger')$$


delete from t_rule_busin_validator where c_busin_name in ('webAddContractLedger','webSaveContractLedger')$$
delete from t_rule_busin_validator where ID in (50107,50108)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50107, 'webAddContractLedger', 'agreeNo', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50108, 'webAddContractLedger', 'agreeName', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50109, 'webAddContractLedger', 'buyer', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50110, 'webAddContractLedger', 'supplierNo', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50111, 'webAddContractLedger', 'signDate', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50112, 'webAddContractLedger', 'signAddr', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50113, 'webAddContractLedger', 'agreeStartDate', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50114, 'webAddContractLedger', 'agreeEndDate', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50115, 'webAddContractLedger', 'balance', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50116, 'webAddContractLedger', 'checkAccept', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50117, 'webAddContractLedger', 'objectionPeriod', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50118, 'webAddContractLedger', 'deliveryDate', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50119, 'webAddContractLedger', 'deliveryAddr', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50120, 'webAddContractLedger', 'des', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50121, 'webAddContractLedger', 'buyerNo', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50122, 'webAddContractLedger', 'supplier', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50123, 'webSaveContractLedger', 'agreeNo', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50124, 'webSaveContractLedger', 'agreeName', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50125, 'webSaveContractLedger', 'buyer', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50126, 'webSaveContractLedger', 'supplierNo', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50127, 'webSaveContractLedger', 'signDate', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50128, 'webSaveContractLedger', 'signAddr', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50129, 'webSaveContractLedger', 'agreeStartDate', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50130, 'webSaveContractLedger', 'agreeEndDate', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50131, 'webSaveContractLedger', 'balance', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50132, 'webSaveContractLedger', 'checkAccept', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50133, 'webSaveContractLedger', 'objectionPeriod', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50134, 'webSaveContractLedger', 'deliveryDate', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50135, 'webSaveContractLedger', 'deliveryAddr', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50136, 'webSaveContractLedger', 'des', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50137, 'webSaveContractLedger', 'buyerNo', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50138, 'webSaveContractLedger', 'supplier', 1, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50139, 'webSaveContractLedger', 'id', 1, '1', NULL, NULL, NULL, NULL, NULL)$$


delete from t_rule_validator where c_valid_name in ('signAddr','des')$$
INSERT INTO `t_rule_validator` (`C_SYS`, `C_VALID_NAME`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`, `C_DATA_TYPE`, `N_DATA_LEN`, `N_DATA_SCALE`, `F_MAX`, `F_MIN`, `C_VALIDATOR`, `C_PATTERN`, `D_REGDATE`, `D_MODIDATE`, `C_DESCRIPTION`, `C_BUSIN_FIELD`, `C_DEPENDS`, `C_MESSAGE`, `C_REF_VALUE`) VALUES ('SCF', 'signAddr', '签订地点', 'signAddr', '0', 'C', 100, 0, 100, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_validator` (`C_SYS`, `C_VALID_NAME`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`, `C_DATA_TYPE`, `N_DATA_LEN`, `N_DATA_SCALE`, `F_MAX`, `F_MIN`, `C_VALIDATOR`, `C_PATTERN`, `D_REGDATE`, `D_MODIDATE`, `C_DESCRIPTION`, `C_BUSIN_FIELD`, `C_DEPENDS`, `C_MESSAGE`, `C_REF_VALUE`) VALUES ('SCF', 'des', '描述', 'des', '0', 'C', 200, 0, 200, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)$$


delete from t_cfg_snogeneral where c_opertype in ('ContractLedger.id','ContractLedgerRecode.id')$$
INSERT INTO `t_cfg_snogeneral` (`C_OPERTYPE`, `L_LASTNO`, `D_LASTDATE`, `C_SYSNO`, `C_TYPE`, `C_MSG`, `L_DATA_LEN`, `ID`) VALUES ('ContractLedger.id', 1, NULL, 'SCF', '0', NULL, 10, 50009)$$
INSERT INTO `t_cfg_snogeneral` (`C_OPERTYPE`, `L_LASTNO`, `D_LASTDATE`, `C_SYSNO`, `C_TYPE`, `C_MSG`, `L_DATA_LEN`, `ID`) VALUES ('ContractLedgerRecode.id', 1, NULL, 'SCF', '0', NULL, 10, 50012)$$


## -- 添加合同/发票删除标识
delete from t_rule_busin_validator where id in (50140,50141)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50140, 'webAddCustAgreement', 'isDeleted', 21, '1', NULL, NULL, NULL, NULL, NULL)$$
INSERT INTO `t_rule_busin_validator` (`ID`, `C_BUSIN_NAME`, `C_VALID_NAME`, `N_PRIORITY`, `C_STATUS`, `D_REGDATE`, `D_MODIDATE`, `C_SHOW_NAME`, `C_NAME`, `C_MUSTITEM`) VALUES (50141, 'addInvoice', 'isDeleted', 13, '1', NULL, NULL, NULL, NULL, NULL)$$




## -- 最新菜单整理   2017/03/21
delete from t_cfg_menu$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (1, NULL, '基础管理', '基础管理', NULL, NULL, 0, 1, '基础管理', '1', '20160531', '20160531', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (2, NULL, '基金业务', '基金业务', NULL, NULL, 0, 2, '基金业务', '1', '20160531', '20160531', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3, NULL, '理财业务', '理财业务', NULL, NULL, 0, 3, '理财业务', '0', '20160531', '20160531', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (4, NULL, '供应链融资业务', '供应链融资业务', NULL, NULL, 0, 4, '供应链融资业务', '1', '20160531', '20160531', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (5, NULL, '帮助中心', '帮助中心', NULL, NULL, 0, 5, '帮助中心', '0', '20170112', '20170112', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (8, NULL, '公告管理', '公告管理', NULL, NULL, 1, 4, '公告管理', '1', '20160905', '20160905', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (10, NULL, '企业投资', '企业投资', NULL, NULL, 2, 3, '企业投资', '1', '20151207', '20151207', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (11, NULL, '资产信息', '资产信息', 'fundInfo/fundInfo.html', NULL, 10, 2, '资产信息', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (12, NULL, '所有资产', '所有资产', 'fundInfo/fundAllInfo.html', NULL, 10, 3, '所有资产', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (13, NULL, '流程查询', '流程查询', NULL, NULL, 4, 7, '流程查询', '0', '20160918', '20160918', NULL, '0', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (14, NULL, '流程定义', '流程定义', NULL, NULL, 4, 8, '流程定义', '0', '20160918', '20160918', NULL, '0', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (15, NULL, '消息管理', '消息管理', NULL, NULL, 1, 5, '消息管理', '1', '20160909', '20160909', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (20, NULL, '账户管理', '账户管理', NULL, NULL, 1, 2, '账户管理', '1', '20151207', '20151207', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (21, NULL, '账户管理', '账户管理', NULL, NULL, 2, 1, '账户管理', '1', '20170320', '20170320', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (22, NULL, '开通基金业务', '开通基金业务', 'crtcount/addAccount.html#fund', NULL, 21, 1, '开通基金业务', '1', '20151207', '20160509', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (23, NULL, '企业信息', '企业信息', 'custInfo/custInfo.html', NULL, 21, 2, '企业信息', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (30, NULL, '我要交易', '我要交易', NULL, NULL, 2, 4, '我要交易', '1', '20151207', '20151207', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (31, NULL, '产品申购', '产品申购', 'purchase/purchase.html', NULL, 30, 9, '企额宝申购', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (32, NULL, '企额宝申购', '企额宝申购', 'qiefof/qiePurchase.html', NULL, 30, 10, '企额宝申购', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (33, NULL, '产品赎回', '产品赎回', 'redem/redem.html', NULL, 30, 11, '产品赎回', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (34, NULL, '企额宝赎回', '企额宝赎回', 'qiefof/qieRedem.html', NULL, 30, 12, '企额宝赎回', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (35, NULL, '撤销订单', '撤销订单', 'cancel/cancel.html', NULL, 30, 13, '撤销订单', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (36, NULL, '修改分红方式', '修改分红方式', 'purchase/modifyShare.html', NULL, 30, 14, '修改分红方式', '1', '20160715', '20160715', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (40, NULL, '信息查询', '信息查询', NULL, NULL, 2, 5, '信息查询', '1', '20151207', '20151207', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (41, NULL, '交易查询', '交易查询', 'queryInfo/queryCheck.html', NULL, 40, 15, '交易查询', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (42, NULL, '合作机构查询', '合作机构查询', 'queryInfo/queryComp.html', NULL, 40, 16, '合作机构查询', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (43, NULL, '对账单查询', '对账单查询', 'queryInfo/queryAccount.html', NULL, 40, 17, '对账单查询', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (50, NULL, '账户分析', '账户分析', NULL, NULL, 2, 6, '账户分析', '1', '20151207', '20151207', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (51, NULL, '持仓分析', '持仓分析', 'analysis/positionAnalysis.html', NULL, 50, 19, '持仓分析', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (52, NULL, '资产明细', '资产明细', 'analysis/fundDetail.html', NULL, 50, 20, '资产明细', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (53, NULL, '分红明细', '分红明细', 'queryInfo/queryBonus.html', NULL, 50, 30, '资金明细', '1', '20151207', '20151207', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (60, NULL, '审批管理', '审批管理', NULL, NULL, 2, 2, '审批管理', '1', '20151207', '20151207', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (61, NULL, '未审批单据', '未审批单据', 'recheck/unRecheck.html', NULL, 60, 1, '未审批单据', '1', '20151207', '20151207', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (62, NULL, '已审批单据', '已审批单据', 'recheck/recheck.html', NULL, 60, 2, '已审批单据', '1', '20151207', '20151207', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (63, NULL, '流程定义', '流程定义', 'recheck/crtFlow.html', NULL, 60, 3, '流程定义', '1', '20151207', '20151207', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (64, NULL, '定义审批金额段', '定义审批金额段', 'recheck/modiMoney.html', NULL, 60, 4, '定义审批金额段', '1', '20151207', '20151207', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (70, NULL, '个人中心', '个人中心', NULL, NULL, 1, 7, '个人中心', '1', '20170320', '20170320', NULL, '0', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (82, NULL, '保理业务', '保理业务', NULL, NULL, -1, 52, '保理业务', '1', '20160415', '20160415', NULL, '0', '')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (87, NULL, '企业认证', '企业认证', '../../scf/app/account/companyCertificate.html', NULL, 21, 4, '企业认证', '1', '20160415', '20160415', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (100, NULL, '基金风险评测', '基金风险评测', 'report/report.html\r\n', NULL, 30, 8, '基金风险评测', '1', '20160422', '20160422', NULL, '1', NULL)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (200, NULL, '流程监控', '流程监控', '../../scf2/views/flow/flowSearch/flowMonitor.html', NULL, 13, 0, '流程监控', '0', '20160918', '20160918', NULL, '1', '')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (201, NULL, '已办流程', '已办流程', '../../scf2/views/flow/flowSearch/completeFlow.html', NULL, 13, 1, '已办流程', '1', '20160918', '20160918', NULL, '1', '')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (202, NULL, '待办流程', '待办流程', '../../scf2/views/flow/flowSearch/waitFlow.html', NULL, 13, 2, '待办流程', '1', '20160918', '20160918', NULL, '1', '')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (203, NULL, '节点定义', '节点定义', '../../scf2/views/flow/flowDefine/nodeDefine.html', NULL, 14, 3, '节点定义', '1', '20160918', '20160918', NULL, '1', '')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (204, NULL, '流程定义', '流程定义', '../../scf2/views/flow/flowDefine/flowDefine.html', NULL, 14, 4, '流程定义', '1', '20160918', '20160918', NULL, '1', '')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (205, NULL, '角色管理', '角色管理', '../../scf2/views/qiecom/role/roleList.html', NULL, 242, 1, '角色管理', '1', '20160918', '20160918', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (206, NULL, '操作员管理', '操作员管理', '../../scf2/views/qiecom/operator/operatorManage.html', NULL, 242, 2, '操作员管理', '1', '20160918', '20160918', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (212, NULL, '完善资料', '完善资料', 'crtcount/crtcount.html', NULL, 21, 3, '完善资料', '1', '20160415', '20160415', NULL, '1', '')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (215, NULL, '保理产品查询', '保理产品查询', '../../scf/app/business/queryFinanPro.html\n', NULL, -1, 73, '保理产品查询', '1', '20160506', '20160506', NULL, '1', '')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (216, NULL, '融资管理', '融资管理', NULL, NULL, 4, 4, '', '1', '20160830', '20160830', NULL, '0', 'SUPPLIER_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (218, NULL, '融资询价', '融资询价', '../../scf2/views/supplier/apply/inquiry.html', NULL, 216, 2, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (219, NULL, '融资查询', '融资查询', NULL, NULL, 4, 10, '', '1', '20160830', '20160830', NULL, '0', 'SUPPLIER_USER,SELLER_USER,FACTOR_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (223, NULL, '资产管理', '资产管理', NULL, NULL, 4, 5, '', '1', '20160830', '20160830', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (224, NULL, '采购订单', '采购订单', '../../scf2/views/supplier/data/orderManage.html', NULL, 223, 6, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (225, NULL, '贸易合同', '贸易合同', '../../scf2/views/contract/cust/contract.html', NULL, 223, 4, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (226, NULL, '票据池', '票据池', '../../scf2/views/supplier/data/draftManage.html', NULL, 223, 1, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (227, NULL, '应收账款', '应收账款', '../../scf2/views/supplier/data/recieveManage.html', NULL, 223, 2, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (228, NULL, '融资管理', '融资管理', NULL, NULL, 4, 4, '', '1', '20160830', '20160830', NULL, '0', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (230, NULL, '业务管理', '业务管理', NULL, NULL, 4, 4, '', '0', '20160830', '20160830', NULL, '0', 'CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (231, NULL, '贸易背景确认', '贸易背景确认', '../../scf2/views/core/business/recieveEnsure.html', NULL, 20010, 3, '', '1', '20160830', '20160830', NULL, '1', 'CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (232, NULL, '三方协议确认', '三方协议确认', '../../scf2/views/core/business/thridEnsure.html', NULL, 20010, 4, '', '1', '20160830', '20160830', NULL, '1', 'CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (233, NULL, '贷款管理', '贷款管理', NULL, NULL, 4, 3, '', '0', '20160830', '20160830', NULL, '0', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (234, NULL, '融资审批', '融资审批', '../../scf2/views/sfccom/loansManage/loansApprove.html', NULL, 216, 5, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (235, NULL, '融资报价', '融资报价', '../../scf2/views/sfccom/loansManage/inquiry.html', NULL, 216, 3, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (236, NULL, '贷款回收', '贷款回收', NULL, NULL, 4, 4, '', '0', '20160830', '20160830', NULL, '0', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (239, NULL, '融资款项催收查询', '融资款项催收查询', '../../scf2/views/sfccom/loansRecycle/collRecord.html', NULL, 219, 7, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (240, NULL, '坏账确认', '坏账确认', '../../scf2/views/sfccom/loansRecycle/badDebt.html', NULL, 216, 6, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (241, NULL, '汇票列表', '汇票列表', '../../scf2/views/sfccom/loansRecycle/draftList.html', NULL, 236, 5, '', '0', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (242, NULL, '系统管理', '系统管理', NULL, NULL, 1, 6, '系统管理', '1', '20160830', '20160830', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (243, NULL, '发货通知单', '发货通知单', '../../scf2/views/sfccom/config/sendManage.html', NULL, 223, 7, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (244, NULL, '参数设置', '参数设置', '../../scf2/views/sfccom/config/paramSetting.html', NULL, 242, 4, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (246, NULL, '机构列表', '机构列表', '../../scf2/views/supplier/info/agencyList.html#supplier', NULL, 20, 1, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (250, NULL, '机构列表', '机构列表', '../../scf2/views/supplier/info/agencyList.html', NULL, 20, 1, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER,CORE_USER,SELLER_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (253, NULL, '黑名单管理', '黑名单管理', '../../scf2/views/sfccom/manager/blackList.html', NULL, 242, 3, '', '1', '20160830', '20160830', NULL, '1', 'PLATFORM_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (254, NULL, '保理产品定制', '保理产品定制', '../../scf2/views/sfccom/product/productList.html', NULL, 400, 1, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (255, NULL, '授信额度管理', '授信额度管理', '../../scf2/views/sfccom/credit/quotaManage.html', NULL, 292, 2, '', '1', '20160920', '20160920', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (256, NULL, '客户管理', '客户管理', NULL, NULL, 1, 1, '', '1', '20160830', '20160830', NULL, '0', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (257, NULL, '客户资料代录', '客户资料代录', '../../scf2/views/qiecom/record/dataRecord.html', NULL, 256, 2, '', '1', '20160830', '20160830', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (258, NULL, '客户资料代录复核', '客户资料代录复核', '../../scf2/views/qiecom/record/dataRecordRecheck.html', NULL, 256, 3, '', '1', '20160830', '20160830', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (259, NULL, '客户资料变更审核', '客户资料变更审核', '../../scf2/views/qiecom/custumer/changeAudite.html', NULL, 256, 4, '', '1', '20160830', '20160830', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (265, NULL, '保理融资开户', '保理融资开户', '../../scf2/views/supplier/account/scfAccount.html', NULL, 20, 0, '', '0', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (266, NULL, '客户白名单受理', '客户白名单受理', '../../scf2/views/sfccom/whitelist/whiteListAccept.html', NULL, 283, 1, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (267, NULL, '客户白名单审核', '客户白名单审核', '../../scf2/views/sfccom/whitelist/whiteListAudit.html', NULL, 283, 2, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (274, NULL, '发布公告', '发布公告', '../../scf2/views/supplier/notice/noticeList.html', NULL, 8, 1, '', '1', '20160905', '20160905', NULL, '1', 'CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (275, NULL, '未读公告', '未读公告', '../../scf2/views/supplier/notice/unreadNotice.html', NULL, 8, 2, '', '1', '20160905', '20160905', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (276, NULL, '已读公告', '已读公告', '../../scf2/views/supplier/notice/readNotice.html', NULL, 8, 3, '', '1', '20160905', '20160905', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (277, NULL, '消息模板', '消息模板', '../../scf2/views/supplier/message/messageModule.html', NULL, 15, 1, '', '1', '20160909', '20160909', NULL, '1', 'CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (278, NULL, '消息订阅', '消息订阅', '../../scf2/views/supplier/message/messageSub.html', NULL, 15, 2, '', '1', '20160909', '20160909', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (279, NULL, '未读消息', '未读消息', '../../scf2/views/supplier/message/unreadMessage.html', NULL, 15, 3, '', '1', '20160909', '20160909', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (280, NULL, '已读消息', '已读消息', '../../scf2/views/supplier/message/readMessage.html', NULL, 15, 4, '', '1', '20160909', '20160909', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (281, NULL, '客户开户资料审核', '客户开户资料审核', '../../scf2/views/qiecom/custumer/dataAudite.html', NULL, 256, 5, '', '1', '20160918', '20160918', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (282, NULL, '电子合同', '电子合同', '../../scf2/views/contract/trade/financeContract.html', NULL, 330, 4, '', '1', '20160918', '20160918', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (283, NULL, '客户管理', '客户管理', '', NULL, 4, 2, '', '1', '20160830', '20160830', NULL, '0', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (284, NULL, '我的授信', '我的授信', '../../scf2/views/supplier/credit/quotaManage.html', NULL, 292, 1, '', '1', '20161012', '20161012', NULL, '1', 'SELLER_USER,CORE_USER,SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (286, NULL, '保理产品', '保理产品', '../../scf2/views/supplier/product/productList.html', NULL, 293, 1, '', '1', '20161012', '20161012', NULL, '1', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (287, NULL, '保理产品', '保理产品', '../../scf2/views/core/product/productList.html', NULL, 293, 1, '', '1', '20161012', '20161012', NULL, '1', 'CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (290, NULL, '授信合同管理', '授信合同管理', '', NULL, 4, 10, '', '0', '20161019', '20161019', NULL, '0', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (291, NULL, '授信合同', '授信合同', '../../scf2/views/sfccom/credit/quotaContract.html', NULL, 330, 5, '', '1', '20161019', '20161019', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (292, NULL, '额度管理', '额度管理', '', NULL, 4, 1, '', '1', '20161019', '20161019', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (293, NULL, '保理产品', '保理产品', '', NULL, 4, 7, '', '1', '20161019', '20161019', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (294, NULL, '合同管理', '合同管理', '', NULL, 4, 6, '', '0', '20161019', '20161019', NULL, '0', '')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (295, NULL, '证书管理', '证书管理', '', NULL, 1, 3, '', '1', '20161021', '20161021', NULL, '0', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (296, NULL, '数字证书管理', '数字证书管理', '../../scf2/views/qiecom/cert/certManage.html', NULL, 295, 1, '', '1', '20161021', '20161021', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (297, NULL, '客户数字证书管理', '客户数字证书管理', '../../scf2/views/qiecom/cert/custCertManage.html', NULL, 295, 1, '', '1', '20161021', '20161021', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (298, NULL, '修改交易密码', '修改交易密码', '../../scf2/views/passwd/resetPass.html#trade', NULL, 70, 1, '', '1', '20161024', '20161024', NULL, '1', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (299, NULL, '绑定微信账户', '绑定微信账户', '../../scf2/views/wechat/cust/wechatBind.html', NULL, 70, 2, '', '1', '20161024', '20161024', NULL, '1', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (300, NULL, '票据池', '票据池', '../../scf2/views/core/bill/billManage.html', NULL, 223, 1, '', '1', '20161027', '20161027', NULL, '1', 'CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (301, NULL, '采购订单', '采购订单', '../../scf2/views/core/order/orderManage.html', NULL, 223, 6, '', '1', '20161027', '20161027', NULL, '1', 'CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (302, NULL, '应付账款', '应付账款', '../../scf2/views/core/recieve/coreRecieveManage.html', NULL, 223, 3, '', '1', '20161027', '20161027', NULL, '1', 'CORE_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (303, NULL, '商业发票', '商业发票', '../../scf2/views/supplier/invoice/InvoiceManage.html', NULL, 223, 5, '', '1', '20161027', '20161027', NULL, '1', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (308, NULL, '贸易合同', '贸易合同', '../../scf2/views/contract/cust/factorContract.html', NULL, 223, 4, '', '1', '20161030', '20161030', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (309, NULL, '商业发票', '商业发票', '../../scf2/views/sfccom/invoice/InvoiceManage.html', NULL, 223, 5, '', '1', '20161118', '20161118', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (310, NULL, '客户关系管理', '客户关系管理', '../../scf2/home.html#/customerRelation/coreRelationManage', NULL, 20, 2, '', '1', '20161122', '20161122', NULL, '1', 'SUPPLIER_USER,CORE_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (313, NULL, '账户信息', '账户信息', '../../scf2/home.html#/account/accountWay', NULL, 20, 1, '', '1', '20161125', '20161125', NULL, '1', 'SUPPLIER_USER,SELLER_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (314, NULL, '帮助中心', '帮助中心', '', NULL, 5, 1, '', '0', '20170112', '20170112', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (315, NULL, '帮助中心', '帮助中心', '../../scf2/home.html#/help/helpCenter', NULL, 314, 1, '', '0', '20170112', '20170112', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (316, NULL, '帮助', '帮助', '../../scf2/home.html#/help/help', NULL, 314, 2, '', '0', '20170112', '20170112', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (319, NULL, '标准合同维护', '标准合同维护', NULL, NULL, 4, 12, '标准合同维护', '1', '20170320', '20170320', NULL, '0', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (320, NULL, '合同类型维护', '合同类型维护', NULL, NULL, 4, 11, '合同类型维护', '1', '20170104', '20170104', NULL, '0', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (321, NULL, '合同类型登记', '合同类型登记', '../../scf2/home.html#/contractType/contractTypeManage', NULL, 320, 1, '合同类型登记', '1', '20170104', '20170104', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (322, NULL, '合同类型审核', '合同类型审核', '../../scf2/home.html#/contractType/contractTypeAudit', NULL, 320, 2, '合同类型审核', '1', '20170104', '20170104', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (323, NULL, '合同类型查询', '合同类型查询', '../../scf2/home.html#/contractType/contractTypeQuery', NULL, 320, 3, '合同类型查询', '1', '20170104', '20170104', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (324, NULL, '标准合同登记', '标准合同登记', '../../scf2/home.html#/standardContract/list', NULL, 319, 4, '标准合同登记', '1', '20170104', '20170104', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (325, NULL, '标准合同审核', '标准合同审核', '../../scf2/home.html#/standardContract/aduit', NULL, 319, 5, '标准合同审核', '1', '20170104', '20170104', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (326, NULL, '标准合同查询', '标准合同查询', '../../scf2/home.html#/standardContract/query', NULL, 319, 6, '标准合同查询', '1', '20170104', '20170104', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (330, NULL, '合同管理', '合同管理', NULL, NULL, 4, 6, '合同管理', '1', '20170123', '20170123', NULL, '0', 'SUPPLIER_USER,SELLER_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (331, NULL, '贸易合同台账登记', '贸易合同台账登记', '../../scf2/home.html#/sellerContract/list', NULL, 330, 1, '贸易合同台账登记', '1', '20170123', '20170123', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (332, NULL, '贸易合同台账审核', '贸易合同台账审核', '../../scf2/home.html#/sellerContract/aduit', NULL, 330, 2, '贸易合同台账审核', '1', '20170123', '20170123', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (333, NULL, '贸易合同台账查询', '贸易合同台账查询', '../../scf2/home.html#/sellerContract/query', NULL, 330, 3, '贸易合同台账查询', '1', '20170123', '20170123', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (334, NULL, '贸易合同台账登记', '贸易合同台账登记', '../../scf2/home.html#/supplierContract/list', NULL, 330, 1, '贸易合同台账登记', '1', '20170123', '20170123', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (335, NULL, '贸易合同台账审核', '贸易合同台账审核', '../../scf2/home.html#/supplierContract/aduit', NULL, 330, 1, '贸易合同台账审核', '1', '20170123', '20170123', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (336, NULL, '贸易合同台账查询', '贸易合同台账查询', '../../scf2/home.html#/supplierContract/query', NULL, 330, 1, '贸易合同台账查询', '1', '20170123', '20170123', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (400, NULL, '产品管理', '产品管理', '', NULL, 4, 8, '', '1', '20170320', '20170320', NULL, '0', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (601, NULL, '客户信息查询', '客户信息查询', '../../scf2/home.html#/plat/custInfo', NULL, 256, 1, '', '1', '20160918', '20160918', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (602, NULL, '客户信息查询', '客户信息查询', '../../scf2/home.html#/fac/custInfo', NULL, 283, 3, '', '1', '20160918', '20160918', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3333, NULL, '申请融资', '申请融资', '../../scf2/views/supplier/apply/financeRecFlow.html#supplier', NULL, 216, 1, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3334, NULL, '申请融资', '申请融资', '../../scf2/views/supplier/apply/financeRecFlow.html#agency', NULL, 228, 1, '', '1', '20160830', '20160830', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3335, NULL, '融资放款', '融资放款', '../../scf2/views/sfccom/loansManage/loansConfirm.html', NULL, 216, 4, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3336, NULL, '待批融资查询', '待批融资查询', '../../scf2/views/supplier/financeSearch/pendFinance.html', NULL, 219, 1, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3337, NULL, '融资还款查询', '融资还款查询', '../../scf2/views/supplier/financeSearch/repayFinance.html', NULL, 219, 2, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3338, NULL, '历史融资查询', '历史融资查询', '../../scf2/views/supplier/financeSearch/historyFinance.html', NULL, 219, 3, '', '1', '20160830', '20160830', NULL, '1', 'SUPPLIER_USER,SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3339, NULL, '供应商融资查询', '供应商融资查询', '../../scf2/views/sfccom/financeSearch/financeSearch.html#supplier', NULL, 219, 6, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3340, NULL, '经销商融资查询', '经销商融资查询', '../../scf2/views/sfccom/financeSearch/financeSearch.html#agency', NULL, 219, 6, '', '1', '20160830', '20160830', NULL, '1', 'FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3341, NULL, '供应商融资查询', '供应商融资查询', '../../scf2/views/core/financeSearch/financeSearch.html#supplier', NULL, 219, 4, '', '1', '20160830', '20160830', NULL, '1', 'CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3342, NULL, '经销商融资查询', '经销商融资查询', '../../scf2/views/core/financeSearch/financeSearch.html#agency', NULL, 219, 5, '', '1', '20160830', '20160830', NULL, '1', 'CORE_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (3343, NULL, '合同模板管理', '合同模板管理', '../../scf2/home.html#/contract.prototype', NULL, 320, 5, '合同模板管理', '1', '20170104', '20170104', NULL, '1', 'PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (20001, NULL, '流程管理', '流程管理', NULL, NULL, 4, 9, NULL, '1', '20161227', '20161227', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (20002, NULL, '流程定义', '流程定义', '../../scf2/home.html#/process/list', NULL, 20001, 1, NULL, '1', '20161227', '20161227', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (20010, NULL, '我的事务', '我的事务', NULL, NULL, 4, 3, NULL, '1', '20161227', '20161227', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (20011, NULL, '我的待办任务', '我的待办任务', '../../scf2/home.html#/flowTask/backlogTask', NULL, 20010, 1, NULL, '1', '20161227', '20161227', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (20012, NULL, '我的已办任务', '我的已办任务', '../../scf2/home.html#/flowTask/finishedTask', NULL, 20010, 2, NULL, '1', '20161227', '20161227', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (20013, NULL, '流程监控', '流程监控', '../../scf2/home.html#/flowTask/processMonitoring', NULL, 20001, 2, NULL, '1', '20161227', '20161227', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER')$$


