##--合同编号生成 提交日期2017/01/06
delete from t_cfg_snogeneral where C_OPERTYPE in ('LIMIT_102202019_QEQHTZQR','LIMIT_102202019_QEQHTZTZ')$$
INSERT INTO `t_cfg_snogeneral` (`C_OPERTYPE`, `L_LASTNO`, `D_LASTDATE`, `C_SYSNO`, `C_TYPE`, `C_MSG`, `L_DATA_LEN`, `ID`) VALUES ('LIMIT_102202019_QEQHTZQR', 0, NULL, 'SCF', '3', NULL, 5, 50010)$$
INSERT INTO `t_cfg_snogeneral` (`C_OPERTYPE`, `L_LASTNO`, `D_LASTDATE`, `C_SYSNO`, `C_TYPE`, `C_MSG`, `L_DATA_LEN`, `ID`) VALUES ('LIMIT_102202019_QEQHTZTZ', 0, NULL, 'SCF', '3', NULL, 5, 50011)$$


##--添加帮助菜单  提交日期2017/01/12
delete from t_cfg_menu where id in (5,314,315,316)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (5, NULL, '帮助中心', '帮助中心', NULL, NULL, 0, 5, '帮助中心', '1', '20170112', '20170112', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (314, NULL, '帮助中心', '帮助中心', '', NULL, 5, 1, '', '1', '20170112', '20170112', NULL, '0', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (315, NULL, '帮助中心', '帮助中心', '../../scf2/home.html#/help/helpCenter', NULL, 314, 1, '', '1', '20170112', '20170112', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (316, NULL, '帮助', '帮助', '../../scf2/home.html#/help/help', NULL, 314, 2, '', '0', '20170112', '20170112', NULL, '1', 'SUPPLIER_USER,SELLER_USER,CORE_USER,FACTOR_USER,PLATFORM_USER')$$


delete from t_cfg_menu where id in (331,332,333,334,335,336)$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (331, NULL, '贸易合同台账登记', '贸易合同台账登记', '../../scf2/home.html#/sellerContract/list', NULL, 330, 1, '贸易合同台账登记', '1', '20170123', '20170123', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (332, NULL, '贸易合同台账审核', '贸易合同台账审核', '../../scf2/home.html#/sellerContract/aduit', NULL, 330, 2, '贸易合同台账审核', '1', '20170123', '20170123', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (333, NULL, '贸易合同台账查询', '贸易合同台账查询', '../../scf2/home.html#/sellerContract/query', NULL, 330, 3, '贸易合同台账查询', '1', '20170123', '20170123', NULL, '1', 'SELLER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (334, NULL, '贸易合同台账登记', '贸易合同台账登记', '../../scf2/home.html#/supplierContract/list', NULL, 330, 1, '贸易合同台账登记', '1', '20170123', '20170123', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (335, NULL, '贸易合同台账审核', '贸易合同台账审核', '../../scf2/home.html#/supplierContract/aduit', NULL, 330, 1, '贸易合同台账审核', '1', '20170123', '20170123', NULL, '1', 'SUPPLIER_USER')$$
INSERT INTO `t_cfg_menu` (`id`, `c_sys`, `c_name`, `c_title`, `c_url`, `c_target`, `n_parent_id`, `n_order`, `c_description`, `c_status`, `d_regdate`, `d_modidate`, `c_openmode`, `c_endnode`, `C_RULE_LIST`) VALUES (336, NULL, '贸易合同台账查询', '贸易合同台账查询', '../../scf2/home.html#/supplierContract/query', NULL, 330, 1, '贸易合同台账查询', '1', '20170123', '20170123', NULL, '1', 'SUPPLIER_USER')$$

