##-- DDL语句
##
##-- V1.0
##
##-- 表结构非空修改 提交日期2017/05/27

drop PROCEDURE if EXISTS create_table_sys_business_type$$
create procedure create_table_sys_business_type() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_business_type')
	THEN
CREATE TABLE `t_sys_business_type` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`C_CODE` VARCHAR(10) NOT NULL COMMENT '业务类型编码',
	`C_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '业务类型名称',
	`C_CREDIT_FLAG` CHAR(1) NULL DEFAULT NULL COMMENT '授信标志',
	`L_MOCK_DATA_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '预览数据编号',
	`C_COMMENTS` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`N_VERSION` BIGINT(20) NULL DEFAULT NULL COMMENT '数据版本',
	PRIMARY KEY (`ID`, `C_CODE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_business_type()$$
drop PROCEDURE if EXISTS create_table_sys_business_type$$




drop PROCEDURE if EXISTS create_table_sys_contract$$
create procedure create_table_sys_contract() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract')
	THEN
CREATE TABLE `t_sys_contract` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`C_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '电子合同编号',
	`C_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '电子合同名称',
	`C_TYPE` CHAR(2) NULL DEFAULT NULL COMMENT '类型 1 模板  2 自定义',
	`L_TYPE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '合同类型',
	`L_STANDARD_TYPE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '标准合同类型',
	`L_DATA_SOURCE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '数据源编号',
	`L_ORIGIN_HTML` BIGINT(20) NULL DEFAULT NULL COMMENT '合同原始html',
	`L_ORIGIN_PDF` BIGINT(20) NULL DEFAULT NULL COMMENT '合同原始pdf',
	`D_SIGN_START_DATE` CHAR(8) NULL DEFAULT NULL COMMENT '签署开始日期',
	`T_SIGN_START_TIME` CHAR(6) NULL DEFAULT NULL COMMENT '签署开始时间',
	`D_SIGN_END_DATE` CHAR(8) NULL DEFAULT NULL COMMENT '签署结束日期',
	`T_SIGN_END_TIME` CHAR(6) NULL DEFAULT NULL COMMENT '签署结束时间',
	`L_SIGN_PDF` BIGINT(20) NULL DEFAULT NULL COMMENT '签署后pdf',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`L_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '公司',
	`C_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '公司名称',
	`C_OPERORG` VARCHAR(200) NULL DEFAULT NULL COMMENT '机构',
	`D_MODI_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_MODI_TIME` CHAR(6) NULL DEFAULT NULL,
	`C_MODI_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_MODI_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`T_REG_TIME` CHAR(6) NULL DEFAULT NULL,
	`D_REG_DATE` CHAR(8) NULL DEFAULT NULL,
	`C_REG_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_REG_OPERID` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract()$$
drop PROCEDURE if EXISTS create_table_sys_contract$$


drop PROCEDURE if EXISTS create_table_sys_contract_corp_account$$
create procedure create_table_sys_contract_corp_account() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_corp_account')
	THEN
CREATE TABLE `t_sys_contract_corp_account` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`C_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '名称',
	`C_TYPE` CHAR(2) NULL DEFAULT NULL COMMENT '类型',
	`C_ORG_CODE` VARCHAR(20) NULL DEFAULT NULL COMMENT '组织机构代码',
	`C_IDENT_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '身份证号',
	`C_ACCOUNT` VARCHAR(20) NULL DEFAULT NULL COMMENT '帐号',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`L_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '公司',
	`C_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '公司名称',
	`C_OPERORG` VARCHAR(200) NULL DEFAULT NULL COMMENT '机构',
	`L_SERVICE_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '电子合同服务商编号',
	`C_SERVICE_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '电子合同服务商名称',
	`L_SIGNER_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '电子合同签署人编号',
	`L_SIGNER_OPERID` BIGINT(20) NULL DEFAULT NULL COMMENT '电子合同签署人操作员编号',
	`C_SIGNER_OPERNAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '电子合同签署人操作员名称',
	`C_SIGNER_ACCOUNT` VARCHAR(20) NULL DEFAULT NULL COMMENT '电子合同签署人帐号',
	`C_SIGNER_MOBILE_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '电子合同签署人手机号',
	`D_MODI_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_MODI_TIME` CHAR(6) NULL DEFAULT NULL,
	`C_MODI_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_MODI_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`T_REG_TIME` CHAR(6) NULL DEFAULT NULL,
	`D_REG_DATE` CHAR(8) NULL DEFAULT NULL,
	`C_REG_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_REG_OPERID` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_corp_account()$$
drop PROCEDURE if EXISTS create_table_sys_contract_corp_account$$



drop PROCEDURE if EXISTS create_table_sys_contract_data_source$$
create procedure create_table_sys_contract_data_source() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_data_source')
	THEN
CREATE TABLE `t_sys_contract_data_source` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`C_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '名称',
	`C_TYPE` CHAR(2) NULL DEFAULT NULL COMMENT '类型',
	`C_DATA` LONGTEXT NULL COMMENT '数据',
	`C_EXTERNAL_DATA` LONGTEXT NULL COMMENT '外部数据',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`L_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '公司',
	`C_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '公司名称',
	`C_OPERORG` VARCHAR(200) NULL DEFAULT NULL COMMENT '机构',
	`D_MODI_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_MODI_TIME` CHAR(6) NULL DEFAULT NULL,
	`C_MODI_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_MODI_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`T_REG_TIME` CHAR(6) NULL DEFAULT NULL,
	`D_REG_DATE` CHAR(8) NULL DEFAULT NULL,
	`C_REG_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_REG_OPERID` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_data_source()$$
drop PROCEDURE if EXISTS create_table_sys_contract_data_source$$



drop PROCEDURE if EXISTS create_table_sys_contract_signer_account$$
create procedure create_table_sys_contract_signer_account() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_signer_account')
	THEN
CREATE TABLE `t_sys_contract_signer_account` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`L_OPERID` BIGINT(20) NULL DEFAULT NULL COMMENT '操作员编号',
	`C_OPERNAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '操作员名称',
	`C_MOBILE_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '手机号码',
	`C_IDENT_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '身份证号',
	`C_ACCOUNT` VARCHAR(20) NULL DEFAULT NULL COMMENT '帐号',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`C_OPERORG` VARCHAR(200) NULL DEFAULT NULL COMMENT '机构',
	`L_SERVICE_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '电子合同服务商编号',
	`C_SERVICE_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '电子合同服务商名称',
	`D_MODI_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_MODI_TIME` CHAR(6) NULL DEFAULT NULL,
	`C_MODI_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_MODI_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`T_REG_TIME` CHAR(6) NULL DEFAULT NULL,
	`D_REG_DATE` CHAR(8) NULL DEFAULT NULL,
	`C_REG_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_REG_OPERID` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_signer_account()$$
drop PROCEDURE if EXISTS create_table_sys_contract_signer_account$$



drop PROCEDURE if EXISTS create_table_sys_contract_stamper$$
create procedure create_table_sys_contract_stamper() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_stamper')
	THEN
CREATE TABLE `t_sys_contract_stamper` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`C_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '名称',
	`L_ORIGIN_STAMPER` BIGINT(20) NULL DEFAULT NULL COMMENT '原始文件(BATCHNO)',
	`D_ORIGIN_DATE` CHAR(8) NULL DEFAULT NULL COMMENT '原始文件日期',
	`T_ORIGIN_TIME` CHAR(6) NULL DEFAULT NULL COMMENT '原始文件时间',
	`L_STAMPER` BIGINT(20) NULL DEFAULT NULL COMMENT '印章文件',
	`C_STAMPER_DATA` TEXT NULL COMMENT '印章数据',
	`D_MAKE_DATE` CHAR(8) NULL DEFAULT NULL COMMENT '制作日期',
	`T_MAKE_TIME` CHAR(6) NULL DEFAULT NULL COMMENT '制作时间',
	`L_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '所属公司',
	`C_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '所属公司名称',
	`C_OPERORG` VARCHAR(200) NULL DEFAULT NULL COMMENT '所属机构',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`L_REG_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`C_REG_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`D_REG_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_REG_TIME` CHAR(6) NULL DEFAULT NULL,
	`L_MODI_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`C_MODI_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`D_MODI_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_MODI_TIME` CHAR(6) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_stamper()$$
drop PROCEDURE if EXISTS create_table_sys_contract_stamper$$



drop PROCEDURE if EXISTS create_table_sys_contract_standard_type$$
create procedure create_table_sys_contract_standard_type() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_standard_type')
	THEN
CREATE TABLE `t_sys_contract_standard_type` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`C_CODE` VARCHAR(10) NOT NULL COMMENT '类型编码',
	`C_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '类型名称',
	`L_TYPE_ID` BIGINT(20) NOT NULL COMMENT '合同类型',
	`L_BUSIN_TYPE_ID` BIGINT(20) NOT NULL COMMENT '业务类型',
	`D_ENABLE_DATE` VARCHAR(8) NULL DEFAULT NULL COMMENT '启用日期',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态 00 未启用  01 启用',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`N_VERSION` BIGINT(20) NULL DEFAULT NULL COMMENT '数据版本',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_standard_type()$$
drop PROCEDURE if EXISTS create_table_sys_contract_standard_type$$




drop PROCEDURE if EXISTS create_table_sys_contract_stub$$
create procedure create_table_sys_contract_stub() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_stub')
	THEN
CREATE TABLE `t_sys_contract_stub` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`L_CONTRACT_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '电子合同编号',
	`C_SIGNATORY` CHAR(1) NULL DEFAULT NULL COMMENT '签署方',
	`N_SEQUENCE` INT(11) NULL DEFAULT NULL COMMENT '签署顺序',
	`L_OPERID` BIGINT(18) NULL DEFAULT NULL COMMENT '操作员编号',
	`L_OPERNAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '操作员名称',
	`L_CORP_ACCOUNT_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '企业帐号',
	`L_SIGNER_ACCOUNT_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '签署人帐号',
	`L_CORP_SIGNER_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '公司签署人编号',
	`C_POSITION_TYPE` CHAR(2) NULL DEFAULT NULL COMMENT '位置类型',
	`N_PAGINATION` INT(11) NULL DEFAULT NULL COMMENT '页码',
	`N_AXIS_X` INT(11) NULL DEFAULT NULL COMMENT 'X轴',
	`N_AXIS_Y` INT(11) NULL DEFAULT NULL COMMENT 'Y轴',
	`C_KEY_WORD` VARCHAR(50) NULL DEFAULT NULL COMMENT '关键字',
	`D_SIGN_DATE` CHAR(6) NULL DEFAULT NULL COMMENT '签署日期',
	`T_SIGN_TIME` CHAR(6) NULL DEFAULT NULL COMMENT '签署时间',
	`L_SIGN_PDF` BIGINT(20) NULL DEFAULT NULL COMMENT '签署后pdf',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`L_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '公司',
	`C_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '公司名称',
	`C_OPERORG` VARCHAR(200) NULL DEFAULT NULL COMMENT '机构',
	`D_MODI_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_MODI_TIME` CHAR(6) NULL DEFAULT NULL,
	`C_MODI_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_MODI_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`T_REG_TIME` CHAR(6) NULL DEFAULT NULL,
	`D_REG_DATE` CHAR(8) NULL DEFAULT NULL,
	`C_REG_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_REG_OPERID` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_stub()$$
drop PROCEDURE if EXISTS create_table_sys_contract_stub$$




drop PROCEDURE if EXISTS create_table_sys_contract_template$$
create procedure create_table_sys_contract_template() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_template')
	THEN
CREATE TABLE `t_sys_contract_template` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`L_TYPE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '合同类型',
	`L_STANDARD_TYPE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '标准合同类型',
	`C_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '模板名称',
	`C_ORIGIN_APPLY_NO` VARCHAR(50) NULL DEFAULT NULL COMMENT '申请编号',
	`L_ORIGIN_TEMPLATE` BIGINT(20) NULL DEFAULT NULL COMMENT '原始模板',
	`L_ORIGIN_SIMPLE` BIGINT(20) NULL DEFAULT NULL COMMENT '原始示例文件',
	`D_ORIGIN_DATE` CHAR(8) NULL DEFAULT NULL COMMENT '原始文件日期',
	`T_ORIGIN_TIME` CHAR(6) NULL DEFAULT NULL COMMENT '原始文件时间',
	`C_ORIGIN_COMMENT` VARCHAR(100) NULL DEFAULT NULL COMMENT '原始备注',
	`N_ORIGIN_SIGNER_COUNT` BIGINT(20) NULL DEFAULT NULL COMMENT '签署人数量',
	`C_ORIGIN_NO_PATTERN` VARCHAR(50) NULL DEFAULT NULL COMMENT '合同编号模式',
	`L_ORIGIN_OPERID` BIGINT(18) NULL DEFAULT NULL COMMENT '申请人',
	`C_ORIGIN_OPERNAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '申请人',
	`L_TEMPLATE` BIGINT(20) NULL DEFAULT NULL COMMENT '模板文件',
	`D_MAKE_DATE` CHAR(8) NULL DEFAULT NULL COMMENT '制作日期',
	`T_MAKE_TIME` CHAR(6) NULL DEFAULT NULL COMMENT '制作时间',
	`L_MAKE_OPERID` BIGINT(20) NULL DEFAULT NULL COMMENT '制作人',
	`C_MAKE_OPERNAME` VARCHAR(20) NULL DEFAULT NULL COMMENT '制作人名称',
	`C_COMMON` VARCHAR(50) NULL DEFAULT NULL COMMENT '备注',
	`L_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '所属公司',
	`C_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '所属公司名称',
	`C_OPERORG` VARCHAR(200) NULL DEFAULT NULL COMMENT '所属机构',
	`C_TEXT_AUDIT_REMARK` VARCHAR(100) NULL DEFAULT NULL COMMENT '文本审核意见',
	`C_TEXT_AUDIT_STATUS` CHAR(2) NULL DEFAULT '00' COMMENT '文本审核状态  00 未审核  01 审核通过  02 审核不通过',
	`L_TEXT_AUDIT_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`C_TEXT_AUDIT_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`D_TEXT_AUDIT_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_TEXT_AUDIT_TIME` CHAR(6) NULL DEFAULT NULL,
	`C_TEMPLATE_AUDIT_STATUS` CHAR(2) NULL DEFAULT '00' COMMENT '模板审核状态  00 未审核  01 审核通过  02 审核不通过',
	`C_TEMPLATE_AUDIT_REMARK` VARCHAR(100) NULL DEFAULT NULL COMMENT '模板审核意见 ',
	`L_TEMPLATE_AUDIT_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`C_TEMPLATE_AUDIT_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`D_TEMPLATE_AUDIT_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_TEMPLATE_AUDIT_TIME` CHAR(6) NULL DEFAULT NULL,
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT '00' COMMENT '业务状态 00 未使用  01 合同文本   02 合同模板',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`L_REG_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`C_REG_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`D_REG_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_REG_TIME` CHAR(6) NULL DEFAULT NULL,
	`L_MODI_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`C_MODI_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`D_MODI_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_MODI_TIME` CHAR(6) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `CUST_STANDARD_TYPE_UNIQUE_KEY` (`L_CUSTNO`, `L_STANDARD_TYPE_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_template()$$
drop PROCEDURE if EXISTS create_table_sys_contract_template$$




drop PROCEDURE if EXISTS create_table_sys_contract_template_log$$
create procedure create_table_sys_contract_template_log() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_template_log')
	THEN
CREATE TABLE `t_sys_contract_template_log` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`L_TEMPLATE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '合同模板编号',
	`C_TEMPLATE_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '合同模板名称',
	`D_OPER_DATE` CHAR(8) NULL DEFAULT NULL COMMENT '操作日期',
	`T_OPER_TIME` CHAR(6) NULL DEFAULT NULL COMMENT '操作时间',
	`C_OPER_TYPE` CHAR(2) NULL DEFAULT NULL COMMENT '操作类型',
	`C_OPER_CONTENT` VARCHAR(100) NULL DEFAULT NULL COMMENT '操作内容',
	`L_CUSTNO` BIGINT(18) NULL DEFAULT NULL COMMENT '操作公司',
	`C_CUSTNAME` VARCHAR(120) NULL DEFAULT NULL COMMENT '操作公司名称',
	`C_OPERORG` VARCHAR(200) NULL DEFAULT NULL COMMENT '操作机构',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`D_MODI_DATE` CHAR(8) NULL DEFAULT NULL,
	`C_MODI_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_MODI_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`T_REG_TIME` CHAR(6) NULL DEFAULT NULL,
	`D_REG_DATE` CHAR(8) NULL DEFAULT NULL,
	`C_REG_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`L_REG_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`T_MODI_TIME` CHAR(6) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_template_log()$$
drop PROCEDURE if EXISTS create_table_sys_contract_template_log$$




drop PROCEDURE if EXISTS create_table_sys_contract_template_stamp_place$$
create procedure create_table_sys_contract_template_stamp_place() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_template_stamp_place')
	THEN
CREATE TABLE `t_sys_contract_template_stamp_place` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`L_TEMPLATE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '合同模板编号',
	`C_TEMPLATE_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '合同模板名称',
	`C_SIGNATORY` CHAR(1) NULL DEFAULT NULL COMMENT '签约方',
	`N_SEQUENCE` INT(11) NULL DEFAULT NULL COMMENT '签约顺序',
	`C_TYPE` CHAR(2) NULL DEFAULT NULL COMMENT '位置类型',
	`N_PAGINATION` INT(11) NULL DEFAULT NULL COMMENT '页码',
	`N_AXIS_X` INT(11) NULL DEFAULT NULL COMMENT 'X轴',
	`N_AXIS_Y` INT(11) NULL DEFAULT NULL COMMENT 'Y轴',
	`C_KEY_WORD` VARCHAR(40) NULL DEFAULT NULL COMMENT '关键字',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`L_REG_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`C_REG_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`D_REG_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_REG_TIME` CHAR(6) NULL DEFAULT NULL,
	`L_MODI_OPERID` BIGINT(20) NULL DEFAULT NULL,
	`C_MODI_OPERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`D_MODI_DATE` CHAR(8) NULL DEFAULT NULL,
	`T_MODI_TIME` CHAR(6) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_template_stamp_place()$$
drop PROCEDURE if EXISTS create_table_sys_contract_template_stamp_place$$




drop PROCEDURE if EXISTS create_table_sys_contract_type$$
create procedure create_table_sys_contract_type() 
BEGIN
	IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_sys_contract_type')
	THEN
CREATE TABLE `t_sys_contract_type` (
	`ID` BIGINT(20) NOT NULL COMMENT '编号',
	`C_CODE` VARCHAR(10) NOT NULL COMMENT '类型编码',
	`C_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '类型名称',
	`C_BUSIN_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '业务状态',
	`C_DOC_STATUS` CHAR(2) NULL DEFAULT NULL COMMENT '文档状态',
	`N_VERSION` BIGINT(20) NULL DEFAULT NULL COMMENT '数据版本',
	PRIMARY KEY (`ID`, `C_CODE`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
	END IF;
END$$
call create_table_sys_contract_type()$$
drop PROCEDURE if EXISTS create_table_sys_contract_type$$





