##-- 创建附件关系审核临时表	提交日期2016/12/16
drop PROCEDURE if EXISTS create_table_custFileAduitTemp$$
	create procedure create_table_custFileAduitTemp() 
	BEGIN
		IF NOT EXISTS (SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA in (select database()) AND table_name='t_cust_fileaduit_temp')
		THEN
		CREATE TABLE `t_cust_fileaduit_temp` (
		`ID` DECIMAL(18,0) NULL DEFAULT NULL,
		`L_CUSTNO` DECIMAL(18,0) NULL DEFAULT NULL,
		`N_COUNT` DECIMAL(5,0) NULL DEFAULT NULL,
		`C_STATUS` VARCHAR(1) NULL DEFAULT NULL,
		`C_TYPE` VARCHAR(60) NULL DEFAULT NULL,
		`C_DESCRIPTION` VARCHAR(200) NULL DEFAULT NULL,
		`D_REGDATE` VARCHAR(8) NULL DEFAULT NULL,
		`D_REGTIME` VARCHAR(8) NULL DEFAULT NULL,
		`D_MODIDATE` VARCHAR(15) NULL DEFAULT NULL,
		`C_OPERNO` VARCHAR(8) NULL DEFAULT NULL,
		`L_ADUIT_CUSTNO` DECIMAL(18,0) NULL DEFAULT NULL,
		`C_ADUITORNO` VARCHAR(8) NULL DEFAULT NULL,
		`D_ADUIT_DATE` VARCHAR(15) NULL DEFAULT NULL,
		UNIQUE INDEX `PK_CUST_FILEADUIT` (`ID`, `L_CUSTNO`, `C_TYPE`)
		);
		END IF;
	END$$
call create_table_custFileAduitTemp()$$
drop PROCEDURE if EXISTS create_table_custFileAduitTemp$$